// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/data/projectsData.js
var projects = [
  {
    id: 1,
    title: "Ingenium AI",
    shortDescription: "AI engineering ecosystem for African students",
    fullDescription: "A comprehensive AI engineering platform featuring a problem solver covering 15 disciplines with image input, 100+ calculators from beginner to PhD level with AI explanations, a project generator with Naira-based budgets, and an expert community. Co-founded with St. Nicholas Sobowale.",
    tags: ["React", "Supabase", "AI", "SaaS", "TypeScript"],
    liveUrl: "https://ingeniumai.tech",
    githubUrl: "https://github.com/zion-robotics",
    status: "live",
    category: "SaaS",
    featured: true,
    achievement: "\u{1F3C6} Top 3 \xB7 Mechatronics Inter-Varsity Competition \xB7 9 universities"
  },
  {
    id: 2,
    title: "SentryAI",
    shortDescription: "AI omnichannel business inbox for African SMEs",
    fullDescription: "AI-powered omnichannel business inbox unifying WhatsApp, email, and social into one smart dashboard. Groq-powered AI responds in Nigerian Pidgin and English. Backend on Alibaba Cloud, frontend on Vercel. Built for the Qwen Cloud Global AI Hackathon 2026.",
    tags: ["React", "TypeScript", "Node.js", "Supabase", "Groq", "Alibaba Cloud"],
    liveUrl: "https://sentryai.vercel.app/",
    githubUrl: "https://github.com/zion-robotics/sentryai",
    status: "Version 1 shipped",
    category: "Hackathon",
    featured: true
  },
  {
    id: 3,
    title: "StudyPal",
    shortDescription: "Offline-first AI study companion for working students",
    fullDescription: "AI reads uploaded notes aloud in 10\u201315 minute sessions then runs comprehension checks. Offline-first PWA that works without internet after first load and syncs automatically. Daily Pulse shows real study coverage, streaks, and performance \u2014 no motivational filler. Built for YPIT Hackathon 2026.",
    tags: ["React", "PWA", "AI", "TypeScript", "Groq"],
    liveUrl: "https://studypal-your-ai-study-companion.vercel.app/",
    githubUrl: "https://github.com/zion-robotics/studypal-your-ai-study-companion",
    status: "live",
    category: "Hackathon",
    featured: true
  },
  {
    id: 4,
    title: "EcoConnect",
    shortDescription: "AI economic platform across 10 African countries",
    fullDescription: "AI platform connecting informal traders and job seekers across Africa. Job matching via OpenRouter/Groq returns top 3 matches with scores. Squad API handles payments without a bank account. Covers 10 African countries, 7 languages, builds trust scores from payment behaviour. Built for Squad Hackathon 3.0.",
    tags: ["React", "OpenRouter", "Groq", "Node.js", "AI"],
    liveUrl: "https://ecoconnect-intelligent-economy.vercel.app/",
    githubUrl: "https://github.com/zion-robotics/ecoconnect-intelligent-economy",
    status: "live",
    category: "Hackathon",
    featured: false
  },
  {
    id: 5,
    title: "SwarmDesk",
    shortDescription: "AI support dashboard with blockchain agent memory",
    fullDescription: "AI customer support dashboard where each agent runs on an isolated memory branch on the Sui blockchain via MemForks. High-confidence resolutions merge into company-wide memory instantly. Real-time streaming chat, light/dark mode, onboarding tour. Built for MemForks Bounty Event.",
    tags: ["React", "TypeScript", "Sui Blockchain", "MemForks", "AI"],
    liveUrl: "https://memforks-liard.vercel.app/",
    githubUrl: "https://github.com/zion-robotics/memforks/tree/main/apps/swarmdesk",
    status: "live",
    category: "Hackathon",
    featured: false
  },
  {
    id: 6,
    title: "PageMind",
    shortDescription: "Chrome extension that summarizes any webpage with AI",
    fullDescription: "AI webpage summarizer Chrome extension (MV3) delivering bullet points, key insights, and reading time. Uses density scoring to pull readable text while filtering navbars, ads, and footers. Caches summaries per URL for 30 minutes. Groq API calls go through the background service worker so the key never touches the content script.",
    tags: ["Chrome Extension", "MV3", "Groq", "JavaScript", "AI"],
    liveUrl: "https://github.com/zion-robotics/AI-page-summarizer-Chrome-extension",
    githubUrl: "https://github.com/zion-robotics/AI-page-summarizer-Chrome-extension",
    status: "live",
    category: "Tool",
    featured: false
  },
  {
    id: 7,
    title: "LitePress",
    shortDescription: "Browser-based file utility \u2014 compression & PDF conversion",
    fullDescription: "Runs entirely in the browser with no server uploads. Supports image compression, image-to-PDF, PDF-to-Word, and Word-to-PDF. Drag-to-reorder for unlimited images. Built with React, TypeScript, Vite, and Tailwind CSS. Open source.",
    tags: ["React", "TypeScript", "Vite", "Tailwind CSS", "Open Source"],
    liveUrl: "https://litepress.tech",
    githubUrl: "https://github.com/zion-robotics/litepress-spark",
    status: "live",
    category: "Tool",
    featured: true
  },
  {
    id: 8,
    title: "Bioresonance Africa",
    shortDescription: "Ecommerce & clinic site for a Lagos health clinic",
    fullDescription: "Full ecommerce platform for a bioresonance therapy clinic in Lagos \u2014 product listings, Paystack payment integration, Sanity CMS blog, branded email, and appointment/contact system.",
    tags: ["React", "Sanity CMS", "Ecommerce"],
    liveUrl: "https://www.1stbioresonanceistofafrica.com/",
    githubUrl: null,
    status: "live",
    category: "Client Work",
    featured: false
  },
  {
    id: 9,
    title: "Habit Tracker PWA",
    shortDescription: "Mobile-first PWA for daily habit tracking",
    fullDescription: "Full auth flow with per-user habit isolation and offline app shell via service worker. 80% test coverage across unit, integration, and end-to-end Playwright test suites.",
    tags: ["React", "PWA", "Playwright", "TypeScript"],
    liveUrl: "https://habit-tracker-lilac-theta.vercel.app/",
    githubUrl: "https://github.com/zion-robotics/habit-tracker",
    status: "live",
    category: "Tool",
    featured: false
  }
];

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "Return all featured projects in Adeogun Daniel Joseph's portfolio with descriptions, tags, and live URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get full details of one portfolio project by its title (case-insensitive substring match).",
  inputSchema: {
    title: z.string().min(1).describe("Project title or substring, e.g. 'litepress', 'ingenium', 'bioresonance'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ title }) => {
    const q = title.toLowerCase();
    const match = projects.find((p) => p.title.toLowerCase().includes(q));
    if (!match) {
      return { content: [{ type: "text", text: `No project matches "${title}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(match, null, 2) }],
      structuredContent: { project: match }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_contact_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get contact information and social links for Adeogun Daniel Joseph (Zion Robotics).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Adeogun Daniel Joseph",
      brand: "Zion Robotics",
      role: "Full-stack developer, robotics builder, SaaS founder",
      website: "https://zionrobotics.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "zion-robotics-mcp",
  title: "Zion Robotics Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for exploring Adeogun Daniel Joseph's (Zion Robotics) portfolio. Use list_projects to see all work, get_project for detail on a single project, and get_contact_info for how to reach out.",
  tools: [list_projects_default, get_project_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
