// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/data/projectsData.js
var projects = [
  {
    id: 1,
    title: "Litepress",
    shortDescription: "A browser-based file utility for converting and compressing files",
    fullDescription: "A web-based file utility tool that lets users convert images to PDF, PDF to Word, Word to PDF, and compress images \u2014 all in the browser. Built solo as a practical SaaS tool.",
    tags: ["React", "File Conversion", "SaaS"],
    liveUrl: "https://litepress.tech",
    status: "live",
    featured: true
  },
  {
    id: 2,
    title: "Ingenium AI",
    shortDescription: "An AI-powered engineering intelligence platform for the developing world",
    fullDescription: "A comprehensive engineering platform featuring an AI problem solver, 100+ engineering calculators across every discipline, a smart project generator with local Nigerian supplier links, a component marketplace, and an expert community. Built to give engineers in Africa access to the tools and knowledge they deserve. Co-founded and built with St. Nicholas Sobowale.",
    tags: ["AI", "SaaS", "Engineering", "React"],
    liveUrl: "https://ingeniumai.tech",
    status: "live",
    featured: true
  },
  {
    id: 3,
    title: "Bioresonance Nigeria",
    shortDescription: "Full ecommerce website for a Lagos-based bioresonance health clinic",
    fullDescription: "A complete ecommerce platform for a bioresonance therapy clinic in Lagos \u2014 featuring product listings, Paystack payment integration, a Sanity CMS-powered blog, branded email, and a full appointment/contact system.",
    tags: ["Ecommerce", "Paystack", "Sanity CMS", "React"],
    liveUrl: "https://www.1stbioresonanceistofafrica.com/",
    status: "live",
    featured: true
  }
];

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "Return all featured projects in Adeogun Daniel Joseph's portfolio with descriptions, tags, and live URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get full details of one portfolio project by its title (case-insensitive substring match).",
  inputSchema: {
    title: z.string().min(1).describe("Project title or substring, e.g. 'litepress', 'ingenium', 'bioresonance'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ title }) => {
    const q = title.toLowerCase();
    const match = projects.find((p) => p.title.toLowerCase().includes(q));
    if (!match) {
      return { content: [{ type: "text", text: `No project matches "${title}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(match, null, 2) }],
      structuredContent: { project: match }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Get contact information and social links for Adeogun Daniel Joseph (Zion Robotics).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Adeogun Daniel Joseph",
      brand: "Zion Robotics",
      role: "Full-stack developer, robotics builder, SaaS founder",
      website: "https://zionrobotics.com"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "zion-robotics-mcp",
  title: "Zion Robotics Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for exploring Adeogun Daniel Joseph's (Zion Robotics) portfolio. Use list_projects to see all work, get_project for detail on a single project, and get_contact_info for how to reach out.",
  tools: [list_projects_default, get_project_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
